import { faGoogle, faSquareFacebook } from '@fortawesome/free-brands-svg-icons';
import {
  faArrowLeft,
  faArrowRightFromBracket,
  faBook,
  faCartFlatbed,
  faCartShopping,
  faCircleInfo,
  faCubes,
  faGlassWater,
  faHandHoldingHeart,
  faMugHot,
  faTrailer,
  faUser,
  faUtensils,
  faMagnifyingGlass,
  faStar,
  faBars,
  faPencil,
  faCreditCard,
  faBasketShopping,
  faHeadset,
  faTrash,
  faXmark,
  faBagShopping,
  faShare,
  faHeart,
  faList,
  faTableCellsLarge,
  faShop,
  faTruckFast,
  faGift,
  faLocationDot,
  faPhone,
  faLocationArrow,
  faMoneyCheck,
  faMapLocationDot,
  faIdCard,
  faCheck,
  faCircleCheck,
  faEnvelope,
  faBell,
  faUserTie,
  faArrowRight,
  faImage,
  faImages,
  faDiceSix,
  faEye,
  faEyeSlash,
  faCalendar,
  faBan,
  faChartSimple,
  faBug,
  faCalendarCheck,
  faCalendarXmark,
  faQrcode,
  faShuffle,
  faClock,
  faPercent,
  faTag,
  faArrowDown,
  faTags,
  faCircleNotch,
  faNoteSticky,
  faClockRotateLeft
} from '@fortawesome/free-solid-svg-icons';
import { Icon } from 'src/app/core/models/icon.model';

export const icons: Icon = {
  faUser: faUser,
  faBook: faBook,
  faArrowLeft: faArrowLeft,
  faArrowRight: faArrowRight,
  faMugHot: faMugHot,
  faGlassWater: faGlassWater,
  faCubes: faCubes,
  faCartShopping: faCartShopping,
  faTrailer: faTrailer,
  faCartFlatbed: faCartFlatbed,
  faHandHoldingHeart: faHandHoldingHeart,
  faCircleInfo: faCircleInfo,
  faArrowRightFromBracket: faArrowRightFromBracket,
  faUtensils: faUtensils,
  faMagnifyingGlass: faMagnifyingGlass,
  faStar: faStar,
  faBars: faBars,
  faPencil: faPencil,
  faCreditCard: faCreditCard,
  faBasketShopping: faBasketShopping,
  faHeadset: faHeadset,
  faTrash: faTrash,
  faXmark: faXmark,
  faBagShopping: faBagShopping,
  faShare: faShare,
  faHeart: faHeart,
  faList: faList,
  faTableCellsLarge: faTableCellsLarge,
  faShop: faShop,
  faTruckFast: faTruckFast,
  faGift: faGift,
  faLocationDot: faLocationDot,
  faPhone: faPhone,
  faLocationArrow: faLocationArrow,
  faMoneyCheck: faMoneyCheck,
  faGoogle: faGoogle,
  faSquareFacebook: faSquareFacebook,
  faMapLocationDot: faMapLocationDot,
  faIdCard: faIdCard,
  faCircleCheck: faCircleCheck,
  faEnvelope: faEnvelope,
  faBell: faBell,
  faUserTie: faUserTie,
  faCheck: faCheck,
  faImage: faImage,
  faImages: faImages,
  faDiceSix: faDiceSix,
  faEye: faEye,
  faEyeSlash: faEyeSlash,
  faCalendar: faCalendar,
  faBan: faBan,
  faChartSimple: faChartSimple,
  faBug: faBug,
  faCalendarCheck: faCalendarCheck,
  faCalendarXmark: faCalendarXmark,
  faQrcode: faQrcode,
  faClock: faClock,
  faPercent: faPercent,
  faTag: faTag,
  faArrowDown: faArrowDown,
  faTags: faTags,
  faCircleNotch: faCircleNotch,
  faShuffle: faShuffle,
  faNoteSticky: faNoteSticky,
  faClockRotateLeft: faClockRotateLeft
};
