import {
  faArrowLeft,
  faArrowRightFromBracket,
  faBook,
  faCartFlatbed,
  faCartShopping,
  faCircleInfo,
  faCubes,
  faGlassWater,
  faHandHoldingHeart,
  faMugHot,
  faTrailer,
  faUser,
  faUtensils,
  faMagnifyingGlass,
  faStar,
  faBars,
  faPencil,
  faCreditCard,
  faBasketShopping,
  faHeadset,
  faTrash
} from '@fortawesome/free-solid-svg-icons';
import { Icon } from 'src/app/core/models/icon.model';

export const icons: Icon = {
  faUser: faUser,
  faBook: faBook,
  faArrowLeft: faArrowLeft,
  faMugHot: faMugHot,
  faGlassWater: faGlassWater,
  faCubes: faCubes,
  faCartShopping: faCartShopping,
  faTrailer: faTrailer,
  faCartFlatbed: faCartFlatbed,
  faHandHoldingHeart: faHandHoldingHeart,
  faCircleInfo: faCircleInfo,
  faArrowRightFromBracket: faArrowRightFromBracket,
  faUtensils: faUtensils,
  faMagnifyingGlass: faMagnifyingGlass,
  faStar: faStar,
  faBars: faBars,
  faPencil: faPencil,
  faCreditCard: faCreditCard,
  faBasketShopping: faBasketShopping,
  faHeadset: faHeadset,
  faTrash: faTrash
};
